name: ubuntubudgie-theme-snap
version: '0.1'
architectures:
  - all
summary: "UbuntuBudgie-Theme: Themes and icons for the budgie desktop."
description: '
  This snap contains multiple packages that are recommended for using the
  ubuntu budgie theme in snaps. This includes xxxxx and yyyy fonts. These are
  the same fonts that are recommended when installing ubuntubudgie-theme.

  In addition, this snap contains the pocillo icon pack as this package
  contains useful pocillo specific icons.

  This snap provides all the Pocillo themes. To see how to
  connect this snap to other packages please see the README in the source
  repository for the snap.

  Attribution
  This snap is packaged by the ubuntu budgie team pocillo-gtk-theme. It is licenced under a xxxx licence
  and can be found here.
    https://github.com/ubuntubudgie/pocillo-gtk-theme

  Similarly, pocillo icon themes are provided by the Ubuntu Budgie team. It is under a xxxx licence.
    https://github.com/ubuntubudgie/pocillo-icon-theme'

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Pocillo
        - $SNAP/share/gtk2/Pocillo-slim
        - $SNAP/share/gtk2/Pocillo-dark
        - $SNAP/share/gtk2/Pocillo-dark-slim
        - $SNAP/share/gtk2/Pocillo-light
        - $SNAP/share/gtk2/Pocillo-light-slim
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Pocillo
        - $SNAP/share/themes/Pocillo-slim
        - $SNAP/share/themes/Pocillo-dark
        - $SNAP/share/themes/Pocillo-dark-slim
        - $SNAP/share/themes/Pocillo-light
        - $SNAP/share/themes/Pocillo-light-slim
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Pocillo
        - $SNAP/share/icons/Moka

parts:
  pocillo-icon-theme:
    after: [utils]
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/pocillo-icon-theme_0.12.3_all.deb
    override-build: |
      snapcraftctl build
      # Don't include app and panel icons to reduce size as they aren't
      # generally useful in the snap. If an app does attempt to display
      # another app's icon by it's name that could be an issue, however
      # that's a corner case.
      find $SNAPCRAFT_PART_INSTALL/usr/share/icons -name apps | xargs rm -rf
      find $SNAPCRAFT_PART_INSTALL/usr/share/icons -name panel | xargs rm -rf
      for dir in $SNAPCRAFT_PART_INSTALL/usr/share/icons/*/; do
        if [ -f $dir/index.theme ]; then
          gtk-update-icon-cache -q $dir
        fi
      done

      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      mv $SNAPCRAFT_PART_INSTALL/usr/share/icons/* $SNAPCRAFT_PART_INSTALL/share/icons/
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/Pocillo

  moka-icon-theme:
    after: [utils]
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/m/moka-icon-theme/moka-icon-theme_5.4.0.1-1_all.deb
    override-build: |
      snapcraftctl build
      # Don't include app and panel icons to reduce size as they aren't
      # generally useful in the snap. If an app does attempt to display
      # another app's icon by it's name that could be an issue, however
      # that's a corner case.
      find $SNAPCRAFT_PART_INSTALL/usr/share/icons -name apps | xargs rm -rf
      find $SNAPCRAFT_PART_INSTALL/usr/share/icons -name panel | xargs rm -rf
      for dir in $SNAPCRAFT_PART_INSTALL/usr/share/icons/*/; do
        if [ -f $dir/index.theme ]; then
          gtk-update-icon-cache -q $dir
        fi
      done

      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      mv $SNAPCRAFT_PART_INSTALL/usr/share/icons/* $SNAPCRAFT_PART_INSTALL/share/icons/
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/Moka

  pocillo-gtk-theme:
    after: [utils]
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/ubuntu-budgie-themes_0.12.3_all.deb
    override-build: |
      snapcraftctl build
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/themes/Qogir*

      mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
      mv $SNAPCRAFT_PART_INSTALL/usr/share/themes/* $SNAPCRAFT_PART_INSTALL/share/themes/
      $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
